"""empty message

Revision ID: 5104acbd03af
Revises: 
Create Date: 2020-06-18 00:22:12.358885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104acbd03af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redisid', sa.Integer(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('remote_addr', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('ua_device', sa.String(), nullable=True),
    sa.Column('ua_platform', sa.String(), nullable=True),
    sa.Column('ua_browser', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redisid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hit')
    # ### end Alembic commands ###
